<?php
/**
 * User repository.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use UserBundle\Entity\User;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(User::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Check if user login is unique
     *
     * @param UserBundle\Entity\User $user User entity
     *
     * @return boolean Result
     */
    public function uniqueLogin($user)
    {
        $uniqueUsername = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.username = :username')
            ->setParameter('username', $user->getUsername())
            ->getQuery();

        $unique = $uniqueUsername->getSingleResult();

        return $unique;
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('user');
    }
}
